name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Állítsd be azt a branch-t, amelyre a push esemény triggereli a workflow-t.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Állítsd be a szükséges Node.js verziót.

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages  # A branch, ahova deploy-olni szeretnél
          build_dir: ./dist  # A build kimeneti könyvtár
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}